[workspace]
members = [
  "packages/multi-test",
  "packages/storage-plus",
  "packages/utils",
]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
